[package]
name = "parse_logs"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = 3
panic = "unwind"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = {version = "0.4.19", features = ["serde"] }
regex = "1.5.5"
lazy_static = "1.4.0"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"