version: '3.9'

services:

  parselogs:
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    volumes:
      - "./:/app"
      - /app/target
