name: Test with code coverage

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov 
          chmod +x ./codecov
          chmod +x ./runtests.sh
          ./runtests.sh
          ./codecov